# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

views:
  - name: solutions-platform-$$APPLICATION_NAME$$
    enabled: True
    type: application
    application:
      name: Go & JavaScript Web App
      desc: >
        A three-tier web application with backend implemented in <a href="https://go.dev/">golang</a>
        and a web UI client implemented in JavaScript.
        <p>Owner: $$OWNER$$
        <p>Criticality: $$CRITICALITY$$
    sdlc:
      - type: source
        attrs:
          provider: GitHub
          organization: $$GITHUB_ORGANIZATION$$
          repo: $$GITHUB_REPOSITORY$$
      - type: build
        attrs:
          provider: Google Cloud Build
          project: $$PROJECT_ID$$
          region: $$REGION$$
          tag: one-time-setup
      - type: registry
        attrs:
          provider: Google Artifact Registry
          project: $$PROJECT_ID$$
          region: us
          repo: demo-application
          type: Docker
      - type: deploy
        attrs:
          provider: Google Cloud Build
          project: $$PROJECT_ID$$
          region: $$REGION$$
          tag: build-and-deploy
      - type: service
        attrs:
          provider: Google Cloud Run
          project: $$PROJECT_ID$$
          region: $$REGION$$
          service: demo-application-backend
